env:
  DOCKER_IMAGE: enirolf/hutsbot_app:latest

addons:
  ssh_known_hosts:
    - $SERVER_IP

services:
- docker

before_install:
- docker build -t $DOCKER_IMAGE

stages:
- lint
- dependencies
- test
- deploy

jobs:
  include:
    - stage: lint
      script: docker run --rm $DOCKER_IMAGE tox -e lint
    - stage: dependencies
      script: docker run --rm $DOCKER_IMAGE tox -e dependencies
    - stage: test
      script: docker run --rm $DOCKER_IMAGE tox -e test
    - stage: deploy
      script: skip
      deploy:
        - provider: script
          script: ci/deploy.sh
          on:
            branch: main
