os: linux
dist: bionic
language: minimal

env:
  DOCKER_IMAGE: enirolf/hutsbot:latest

addons:
  ssh_known_hosts:
  - "$SERVER_IP"

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
- docker build --build-arg CONSUMER_KEY=$CONSUMER_KEY --build-arg CONSUMER_SECRET=$CONSUMER_SECRET
  --build-arg ACCESS_TOKEN=$ACCESS_TOKEN --build-arg ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
  -t $DOCKER_IMAGE .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_IMAGE

stages:
- prep
- deploy

jobs:
  include:
  - stage: prep
  - name: Lint
    script: docker run --rm $DOCKER_IMAGE tox -e lint
  - name: Check dependencies
    script: docker run --rm $DOCKER_IMAGE tox -e dependencies
  - name: Test
    script: docker run --rm $DOCKER_IMAGE tox -e test
  - stage: deploy
    script: skip
    deploy:
    - provider: script
      script: ci/deploy.sh
      on:
        branch: main
